### ISSUE TITLE
Make EQUIPEMENT_CODES and ICAO_MODES confugurable

### ISSUE THREAD

**Issue by cleboo** [pierr3/ModeS#1]
Hi Pierre!

Looking into the future I think it would be a good idea to make equipment codes and especially the ICAO_MODES variable configurable since it is very probable that more and more regions will get added to the Mode S region in the future.

Also, we are right now looking into implementing this Mode S thing with our neighbors here in Austria and not everybody will be on board with this immediately and hence it would be nice to manage this using the plugin so our controllers don't have to remember the countries with which this is implemented.

What do you think?

Regards
Clemens

**Comment by pierr3** [comment]
Hi Clemens,

Of course, right now, if you want me to add any airfield/countries to the list, ask! I was planning on making a web interface, that allows each vacc to update where they want ModeS to be used, and the plugin would fetch the data from the web. As for the equipement codes, they are not configurable on purpose, you can propose a change, but I want everyone to have the same String, otherwise the concept of the mode S airspace block will be kinda ruined ;)

Regards

**Comment by cleboo** [comment]
Hi!

Yeah I was thinking more along the lines of an option in the Euroscope configuration (in the ASR file I guess), but a centralized solution would be even better of course! Agree on the equipment string thing :)

Cheers
Clemens

**Comment by pierr3** [comment]
Added an auto update feature!
